/**
 * Model definition and introspection
 */

import { z } from 'zod';
import { ErrorCodes, FrameworkError } from '../errors.js';

// ============================================================================
// Types
// ============================================================================

export interface ModelDefinition {
  name: string;
  fields: Record<string, z.ZodType>;
  relations?: Record<string, RelationDefinition>;
}

export interface RelationDefinition {
  type: 'hasOne' | 'hasMany' | 'belongsTo';
  to: string;
  foreignKey?: string;
}

export interface FieldInfo {
  name: string;
  type: string;
  required: boolean;
  zodType: string;
}

export interface RelationInfo {
  name: string;
  type: 'hasOne' | 'hasMany' | 'belongsTo';
  to: string;
  foreignKey?: string;
}

export interface Model {
  name: string;
  getSchema(): z.ZodObject<Record<string, z.ZodTypeAny>>;
  getFields(): FieldInfo[];
  getRelations(): RelationInfo[];
  inputSchema: z.ZodObject<Record<string, z.ZodTypeAny>>;
  outputSchema: z.ZodObject<Record<string, z.ZodTypeAny>>;
}

// ============================================================================
// Constants
// ============================================================================


/**
 * Validates model name follows PascalCase
 */
function validateModelName(name: string): void {
  const pascalCasePattern = /^[A-Z][a-zA-Z0-9]*$/;

  if (!pascalCasePattern.test(name)) {
    throw new FrameworkError({
      code: ErrorCodes.NAMING_VIOLATION,
      message: `Model name '${name}' must follow PascalCase convention`,
      suggestion: `Rename '${name}' to '${name.charAt(0).toUpperCase() + name.slice(1)}' ensuring first letter is uppercase`,
      docsUrl: '',
      field: 'name',
    });
  }
}

// ============================================================================
// Schema Generation
// ============================================================================

/**
 * Determines if a field should be excluded from input schema
 * (id, timestamps are auto-generated)
 */
function isAutoGeneratedField(name: string): boolean {
  const autoFields = ['id', 'createdAt', 'updatedAt', 'created_at', 'updated_at'];
  return autoFields.includes(name);
}

/**
 * Gets the Zod type name for introspection.
 * Uses instanceof so it works across both Zod v3 and v4.
 */
function getZodTypeName(zodType: z.ZodType): string {
  if (zodType instanceof z.ZodString) return 'string';
  if (zodType instanceof z.ZodNumber) return 'number';
  if (zodType instanceof z.ZodBoolean) return 'boolean';
  if (zodType instanceof z.ZodDate) return 'date';
  if (zodType instanceof z.ZodArray) return 'array';
  if (zodType instanceof z.ZodObject) return 'object';
  if (zodType instanceof z.ZodOptional) return 'optional';
  if (zodType instanceof z.ZodDefault) return 'default';
  if (zodType instanceof z.ZodEnum) return 'enum';
  if (zodType instanceof z.ZodUnion) return 'union';
  return 'unknown';
}

/**
 * Checks if a Zod type is required (not optional)
 */
function isRequiredField(zodType: z.ZodType): boolean {
  return !(zodType instanceof z.ZodOptional) && !(zodType instanceof z.ZodDefault);
}

// ============================================================================
// Model Implementation
// ============================================================================

class ModelImpl implements Model {
  readonly name: string;
  private definition: ModelDefinition;
  private schema: z.ZodObject<Record<string, z.ZodTypeAny>>;

  constructor(definition: ModelDefinition) {
    validateModelName(definition.name);

    this.name = definition.name;
    this.definition = definition;
    this.schema = z.object(definition.fields);
  }

  getSchema(): z.ZodObject<Record<string, z.ZodTypeAny>> {
    return this.schema;
  }

  getFields(): FieldInfo[] {
    const fields: FieldInfo[] = [];

    for (const [name, zodType] of Object.entries(this.definition.fields)) {
      fields.push({
        name,
        type: getZodTypeName(zodType),
        required: isRequiredField(zodType),
        zodType: zodType.constructor.name,
      });
    }

    return fields;
  }

  getRelations(): RelationInfo[] {
    if (!this.definition.relations) {
      return [];
    }

    const relations: RelationInfo[] = [];
    for (const [name, rel] of Object.entries(this.definition.relations)) {
      relations.push({
        name,
        type: rel.type,
        to: rel.to,
        foreignKey: rel.foreignKey,
      });
    }

    return relations;
  }

  /**
   * Schema for create/update operations - excludes auto-generated fields
   */
  get inputSchema(): z.ZodObject<Record<string, z.ZodTypeAny>> {
    const inputFields: Record<string, z.ZodType> = {};

    for (const [name, zodType] of Object.entries(this.definition.fields)) {
      if (!isAutoGeneratedField(name)) {
        inputFields[name] = zodType;
      }
    }

    return z.object(inputFields);
  }

  /**
   * Schema for responses - includes all fields
   */
  get outputSchema(): z.ZodObject<Record<string, z.ZodTypeAny>> {
    return this.schema;
  }
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Defines a data model with automatic convention enforcement
 *
 * @param definition - Model configuration with name and fields
 * @returns Model instance with introspection methods
 * @throws FrameworkError if naming conventions are violated
 */
export function defineModel(definition: ModelDefinition): Model {
  return new ModelImpl(definition);
}

